Clean up init and remove debug from kernel cmdline
ubports/android_device_fairphone_fp2 pull request #5
Opened 2017-01-05 22:01 UTC by mariogrip

This cleans up init, and removes services that is not needed. It also removes debug from kernel cmdline.

2017-01-05 22:14 UTC, mariogrip commented
![](https://github.trello.services/images/mini-trello-icon.png) [Stabilize the device](https://trello.com/c/eZc8Kwrw/17-stabilize-the-device)

2017-01-06 07:59 UTC, peat-psuwit requested changes
I think we should investigate further why the script doesn't start netmgrd. Besides, you shouldn't include the merge commit in the pull request.

2017-01-06 07:59 UTC, peat-psuwit commented on rootdir/root/init.qcom.rc
> -    disabled
init.class_main.sh do start netmgrd depends on ro.use_data_netmgrd property. We should investigate further why this script isn't run.

2017-01-06 07:59 UTC, peat-psuwit commented on rootdir/root/init.qcom.rc
> -    disabled
I don't think this should start. I don't even think this service should be in the init file at all. It should be on Ubuntu part.

2017-01-06 10:30 UTC, smoose-nils commented on rootdir/root/init.qcom.rc
> -    disabled
I agree, the same goes for ril-daemon and qmux services, they should also be started from main. It looks like init.class_main.sh isn't processed at all

2017-01-06 10:40 UTC, smoose-nils commented on rootdir/root/init.qcom.rc
> -    disabled
This is started below

2017-01-06 10:56 UTC, peat-psuwit commented on rootdir/root/init.qcom.rc
> -    disabled
Ok. Just noticed that init.environ.rc, which set PATH variable amongst other things, is blamed for making android container crashes and is commented out of init.rc. This makes many of shell command (for example, start command which starts a service in the Android container) not working at all. I'll find out why init.environ.rc crashes the container and re-adding it to init.rc.

2017-01-06 11:08 UTC, smoose-nils commented on rootdir/root/init.qcom.rc
> -    disabled
I think I found it. Android cannot find getprop. Adding PATH=/system/bin:$PATH to init.class_main.sh makes it work.

2017-01-06 11:19 UTC, peat-psuwit commented on rootdir/root/init.qcom.rc
> -    disabled
The problem is bigger than that. I'll take a look at why init.environ.rc makes Android container crash at all. Qcom's init system is driven by a number of shell script, and patching all of them is not a solution. Besides, there's probably more things that rely on the correct environment variable being set.

2017-08-20 15:23 UTC, closed without merging